# Generated by Django 5.0.4 on 2024-05-02 00:45

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_add_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('header'), name='gin_trgm_ops'), name='article_gin_upper_header'),
        ),
    ]
